### ISSUE TITLE
Support Geographical Coordinates

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf_site#129]
The legacy `rmf_traffic_editor` had an option to describe reference coordinates in WGS84. it also rendered Open Street Map tiles into the canvas. 

We should add support for that here too. Maybe also support other coordinate systems such as SVY21.

**Comment by mxgrey** [comment]
This might be a helpful plugin: https://github.com/edouardpoitras/bevy_slippy_tiles
