### ISSUE TITLE
[Bug]: Wireframe mod does not set wireframe status to newly added models

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf_site#181]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04 Jammy

### Open-RMF installation type

Binaries

### Open-RMF version or commit hash

NA

### ROS distribution

Iron

### ROS installation type

Binaries

### Description of the bug

If wireframe view is enabled and a new model is added, the visual mesh for the new model does not have wireframe enabled. User need to toggle wireframe mode off and on again for all models to switch to wireframe view.

### Steps to reproduce the bug

* Add a model
* Enable wireframe view from toolbar
* Add second model

The second model will not have wireframe view enabled.

**Comment by luca-della-vedova** [comment]
Should be fixed by https://github.com/open-rmf/rmf_site/pull/179/commits/329eb047539aa0b805a2e7cf19549da92cee47cb. I'll merge the PR in if it looks OK

**Comment by Yadunund** [comment]
I don't know as much of bevy but how does your approach compare to having a Wireframe boolean resource that we can update when the view is toggled and we lookup that resource everytime we spawn a model? Instead of system that goes though all the newly added models and then updates their visuals to wireframe?
