### ISSUE TITLE
Consider removing dynamic linking optimization

### ISSUE THREAD

**Issue by luca-della-vedova** [open-rmf/rmf_site#202]
The dynamic linking optimization that we use [here](https://github.com/open-rmf/rmf_site/blob/e852b3465ac41fc56657ad26879b1dd0438c135c/rmf_site_editor/Cargo.toml#L53-L57) does reduce compile times quite significantly (on my machine it went from 55s to 46s), but as noted in the [docs](https://bevyengine.org/learn/book/getting-started/setup/#enable-fast-compiles-optional) it makes redistributing the app more tricky.

Specifically, because (probably?) colcon expects the binary to be statically linked, building the package with colcon and trying to run it results in the following error:

```
[...] error while loading shared libraries: libbevy_dylib-165be36195c0d4d6.so: cannot open shared object file: No such file or directory
```

On the other hand, if we remove the optimization we get longer compile times but `ros2 run` works like a charm.
It's a tradeoff but I believe for greater integration with ROS 2 we should probably drop the dynamic linking (maybe only use it on the local developer workstation if they really want?)

CC @Yadunund @mxgrey for feedback

**Comment by Yadunund** [comment]
Is it possible to conditionally enable the optimization based on some cargo build args?

**Comment by luca-della-vedova** [comment]
I believe we could do a feature flag so people that want to build with dynamic linking could do `cargo run --features dynamic-linking [...]`, that is some extra typing but I'm not sure there is a better way to do it
