### ISSUE TITLE
[Bug]: Not able to add the waypoint inside the lift and door of lift

### ISSUE THREAD

**Issue by VigashiniDotworld** [open-rmf/rmf_site#224]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04

### Open-RMF installation type

Source build

### Open-RMF version or commit hash

2.3.0

### ROS distribution

Humble

### ROS installation type

Source build

### Description of the bug

ERROR librmf_site_editor::site::save: Unable to compile site: an object has a reference to an anchor that does not exist

As this error shows when adding the lift waypoint and not able to save the site and generate the nav graph

### Steps to reproduce the bug

1. Add the lift 
2. Add the waypoint inside the lift and to save the anchor point for further nav graph generation.

### Additional information or screenshots

![Screenshot from 2024-06-08 11-28-41](https://github.com/open-rmf/rmf_site/assets/145435071/b2e3c2f0-ad63-4106-bffb-32361044af20)

**Comment by naveenrobo** [comment]
@mxgrey can you please advise on this

**Comment by luca-della-vedova** [comment]
Can reproduce, looking into it!

**Comment by naveenrobo** [comment]
@luca-della-vedova I suspect it is because the Anchor is still marked "unsaved". When I try loading the demo hotel building.yaml file it works without any issue. I was able to generate nav_graph. it only happens if we try to create the anchor ourselves in site editor.

**Comment by luca-della-vedova** [comment]
Yes I believe it is due to it not being assigned a `SiteID` during site saving

**Comment by luca-della-vedova** [comment]
Give a try to #226 and see if it works for you

**Comment by naveenrobo** [comment]
@luca-della-vedova  working now. I am able to add lift and waypoints inside and save it as well as generate nav_graphs.

Thanks a lot for the quick fix.

**Comment by VigashiniDotworld** [comment]
Thanks for immediate response
