### ISSUE TITLE
[Bug]: rmf_site crashing on model spawn

### ISSUE THREAD

**Issue by tomkimsour** [open-rmf/rmf_site#240]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04

### Open-RMF installation type

Source build

### Open-RMF version or commit hash

humble

### ROS distribution

Humble

### ROS installation type

Binaries

### Description of the bug

I was spawning many OpenRobotics/OfficeChairGrey and after some time the program crashed with the following.
```
thread 'main' panicked at /home/thomasung/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/commands/mod.rs:1022:13:
error[B0003]: Could not insert a bundle (of type `bevy_mod_raycast::deferred::RaycastMesh<librmf_site_editor::interaction::SiteRaycastSet>`) for entity 2459v3 because it doesn't exist in this World.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic when applying buffers for system `librmf_site_editor::interaction::gizmo::make_gizmos_pickable`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!

```

### Steps to reproduce the bug

- cargo run --features bevy/dynamic_linking --release <some_file_path>
- start spawning OpenRobotics/OfficeChairGrey using the editor
- it would crash at some point ?

**Comment by luca-della-vedova** [comment]
Hi!

Can you try https://github.com/open-rmf/rmf_site/pull/238 and see if that works for you? Model spawning was a fairly complex beast and we recently refactored it to avoid precisely these kind of issues

**Comment by mxgrey** [comment]
I'm going to close this on the assumption that #238 fixed the problem, but feel free to reopen if the issue persists with that latest main branch.
